### ISSUE TITLE
Nothing to do report of LineInserter is wrong

### ISSUE THREAD

**Issue by ReikOberrath** [iks-github/MOGLiCodeCreator#21]
ACTUAL:
VelocityModelBasedLineInserter: 

No model matching input artefact found. Nothing to do.
   Report for input artefact 'admin_init_db_script':
   ...

SHOULD BE:
VelocityModelBasedLineInserter: 
No model matching input artefact found. Nothing to do.

Following 2 artefact(s) did not match the model used:
admin_init_db_script
...

**Comment by iks-github** [comment]
Correction of report has been done.
