### ISSUE TITLE
Mediocre performance for big data

### ISSUE THREAD

**Issue by ReikOberrath** [iks-github/MOGLiCodeCreator#43]
To decide whether a model matches to a template, velocity must merge all main templates with the model. For many templates for different models and models with many classes a lot of merges are done in vain which reduces performance. It would be more efficient to merge each template with a reduced model containing only a single class. This would be enough to decide wheter model and template match. If so, the full model can be merged with the template.

**Comment by iks-github** [comment]
Problem is solved for the ClassBasedFileMaker and the ModelBasedLineInserter as suggested.
