### ISSUE TITLE
Number sign not usable for generation

### ISSUE THREAD

**Issue by ReikOberrath** [iks-github/MOGLiCodeCreator#45]
The core of the generation is based on the Velocity framework. Velocity uses the number sign as comment marker. All comments are completely removed during merging a template with the model data. Therefore no number sign can enter the generation output. A mechanism is needed that allows generation output containing number signs. Without such a mechanism no valid shell scripts can be generated.

**Comment by iks-github** [comment]
For the ModelBasedLineInserter and the ClassBasedFileMaker a new artefact property exists: ReplaceToNumberSign. The value of this property will be replaced by the # symbol after velocity has merged model and template and before the output files are written.
